site_name: McKone Lab Handbook
copyright: Copyright &copy; 2023 McKone Lab
theme:
  name: material
  
  features:
    - navigation.instant #instant load
    - navigation.sections # includes top level sections in sidebar
    - navigation.tracking #adds anchors to address bar
    - navigation.tabs #renders top-level sections in header bar
    - navigation.path #breadcrumbs
    - navigation.indexes #creates index pages
    - navigation.top #back to top link
    - navigation.footer #links to previous and next page
    - search.suggest #autocomplete based on suggestion in search bar
    - search.highlight #highlights appearances of search term(s) after search

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav: 
  - Home: index.md
  - About Our Lab: 
    - about/index.md
    - Our ideals: about/mission-vision.md
  - Policies:
    - policies/index.md
    - Lab safety policies: policies/safety.md
    - Interpersonal behavior: policies/interpersonal.md
    - Hours, vacation, and leave: policies/hoursVacationLeave.md 
    - Lab Notebooks: policies/labNotebook.md
    - Onboarding:
      - Onboarding Overview: policies/onboarding.md
      - Initial Safety Training: policies/onboarding_safety.md
      - Experiment 1: policies/expt1.md
  - Professional training:
    - professionalTraining/index.md
    - Reading papers: professionalTraining/readingPapers.md
    - Giving presentations: professionalTraining/givingPresentations.md
    - Documenting your work: professionalTraining/documentingWork.md
    - Guides for Researchers:
      - Guides for researchers: professionalTraining/guides.md
      - Preamble: professionalTraining/noteFromJames.md
      - Grad Students: professionalTraining/gradGuide.md
      - Undergraduates: professionalTraining/ugGuide.md
      - Postdoc researchers: professionalTraining/pdGuide.md
      - Visitors: professionalTraining/visitorGuide.md
  - Technical Training: 
    - technicalTraining/index.md
  
