site_name: McKone Lab Handbook
copyright: Copyright &copy; 2023 McKone Lab
theme:
  name: material
  
  features:
    - navigation.instant #instant load
    - navigation.tracking #adds anchors to address bar
    - navigation.tabs #renders top-level sections in header bar
    - navigation.path #breadcrumbs
    - navigation.top #back to top link
    - navigation.footer #links to previous and next page
    - search.suggest #autocomplete based on suggestion in search bar
    - search.highlight #highlights appearances of search term(s) after search

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav: 
  - Home: 
    - 'index.md'
    - To-Do list: 'to-do.md'
    - 'about.md'
    - Our ideals: 'mission-vision.md'
  - Policies:
    - Onboarding: 'onboarding.md'
    - Offboarding: 'offboarding.md'
    - Safety: 'safety.md'
    - Interpersonal Behavior: 'interpersonal.md'
  - Training resources:
    - Reading papers: 'readingPapers.md'
    - Giving presentations: 'givingPresentations.md'
    - Documenting your work: 'documentingWork.md'
  - Guides:
    - Guides for researchers: 'guides.md'
    - Preamble: 'noteFromJames.md'
    - Grad Students: 'gradGuide.md'
    - Undergraduates: 'ugGuide.md'
    - Postdoc researchers: 'pdGuide.md'
    - Visitors: 'visitorGuide.md'
  
